Что нужно сделать:
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.

spring:
  application:
    name: restDemo

  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: fedor
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

logging:
  level:
    root: info
  pattern:
    console: "%d{HH:mm} %-5level %logger{36} - %msg%n"

jwt:
  secret:
    key: 75a81eedb96be7d57d333aa5aa715ca3c917c8c7711a44201d1e1a3690f399dcee8b2eba
